<!DOCTYPE html>

<!-- Page language set as English New Zealand to attract New Zealand customers -->
<!-- Useful for search engines, screen readers and voice assistants to correctly pronounce content -->
<html lang="en-NZ">

<head>
	<!-- Display the page title in the browser tab to describe the meaning of the page -->
	<title>Privacy</title>

	<!-- Web page author -->
	<meta name="author" content="Tanya Suzette Boshoff">

	<!-- Web page description -->
    <meta name="description" content="Motueka Bed & Breakfast Privacy Statement">

	<!-- The set of characters and symbols used in the web page and required by the browser -->
	<meta charset="utf-8">

	<!-- The browser should not scale content down. Necessary to make the website responsive on all devices -->
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Define keywords required by search engines -->
    <meta name="keywords" content="Motueka, Bed & Breakfast, B&B, Accommodation">

	<!-- Display a favicon image to the left of the page title in the browser tab -->
	<link rel="icon" type="image/x-icon" href="./images/favicon.ico">
</head>
<body>

	<!-- Page header -->
	<header>

		<!-- Page navigation -->
		<nav>

			<!-- Links to additional information contained in other web pages -->
			<section>
				<ul>
					<li><a href="index.php" title="Home page">Home</a></li>
					<li><a href="listrooms.php" title="View rooms">Rooms</a></li>
					<ul>
						<li><a href="addroom.php" title="Add a room">Add a room</a></li>
					</ul>
					<li><a href="listbookings.php" title="View current bookings">Bookings</a></li>
						<ul>
							<li><a href="makebooking.php" title="Make a bookings">Make a booking</a></li>
							<li><a href="#" title="Purchase a gift voucher">Gift vouchers</a></li>
						</ul>
					<li><a href="#" title="About the owners">About</a></li>
						<ul>
							<li><a href="#" title="About the area">The Motueka area</a></li>
						</ul>
					<li><a href="#" title="Contact us">Contact</a></li>	
				</ul>
			</section>

			<!-- Action buttons -->
			<section>
				<ul>
					<li><a href="login.php" title="Log in to your account">Log in</a></li>
					<li><a href="registercustomer.php" title="Register an account">Register</a></li>
					<li><a href="#" title="Your account information">Account</a></li>
				</ul>
			</section>
		</nav>

		<!-- Page heading -->
		<h1>Privacy Statement</h1>
	</header>

	<!-- Main page section -->
	<main>

		<!-- Page section containing the privacy statement -->
		<section>
			<p>This policy outlines how we collect, store, use and share your information in compliance with the Privacy Act 2020 of New Zealand.</p>
			<h2>We collect personal information from you, including information about your:</h2>
			<p>
				<ul>
					<li>name</li>
					<li>contact information</li>
					<li>location</li>
					<li>interactions with us</li>
					<li>customer and room booking identification numbers which are automatically generated by the website/database</li>			
				</ul>
			</p>
			<h2>We collect your personal information in order to:</h2>
			<p>
				<ul>
					<li>register new customers</li>
					<li>add, manage or search existing customer details</li>
					<li>make and manage room bookings</li>
					<li>improve our website analytics</li>
					<li>contact existing customers to confirm their booking details from time to time</li>
					<li>identify and allow non-local visitors to receive marketing content more relevant to them</li>
					<li>make marketing content more relevant to the customer, such as marketing to a customer that browsed the booking process but did not make a booking</li>
				</ul>
			</p>
			<h2>Providing some information is optional:</h2>
			<p>
				<ul>
					<li>If you choose not to enter your home address, we'll be unable to identify you as a non-local visitor and make marketing content more relevant to you.</li>
					<li>If you choose not to allow us to track your GPS location, we'll be unable to improve our website analytics and provide marketing content more relevant to you, if you are a non-local visitor.</li>
					<li>If you choose not to allow us to track your browsing habits, we'll be unable to make marketing content more relevant to you, such as marketing to you if you browsed the booking process but did not make a booking.</li>
				</ul>
			</p>
			<h2>How we store your information:</h2>
			<p>We keep your information safe by storing it in encrypted files and only allowing certain staff to access it.</p>
			<p>We keep your information for seven years if you made a booking and for two years if you only registered an account at which point, we securely destroy it by securely erasing all digital copies.</p>
			<h2>Your rights:</h2>
			<p>You have the right to ask for a copy of any personal information we hold about you, and to ask for it to be corrected if you think it is wrong. You are also allowed to view and update your personal information after logging in to the website. Alternatively, if you’d like to ask for a copy of your information, or to have it corrected, please contact us at TanyaBoshoff@myop.ac.nz, or 021-123-456, or PO Box 123, Christchurch, New Zealand 7600.</p>
		</section>	
	</main>

    <!-- Page footer -->
    <?php include 'footer.php'; ?>
</body>
</html>